version: '3.8'
services:
  mysqldb:
    image: mysql
    platform: linux/amd64
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306:3306

  app:
    build: .
    env_file: ./.env
    environment:
      - MYSQL_HOST=mysqldb
    ports:
      - 3000:3000
    depends_on:
      - mysqldb
