ALTER TABLE user
  ADD gender CHAR NULL,
  ADD birthdate DATE NULL,
  ADD bio VARCHAR(240) NULL,
  ADD createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
